### ISSUE TITLE
请问可以公开代码吗？

### ISSUE THREAD

**Issue by YePG** [WENGSYX/ADBCMM#1]
鲁迅说过，开了github但是没有公开代码的行为都是耍流氓

**Comment by WENGSYX** [comment]
很简单的东西，你直接把不同国家的数据集混合到一起，然后使用transformer的AutoModelForMultipleChoice加载mdeberta的预训练权重，之后使用CE损失进行训练。代码有点乱，最近事情有点多，还没空整理。
